import type { Metadata } from "next";
import { Roboto_Serif as FontSans } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";

import { Locale, i18n } from "../../../i18n-config";

import { Navbar, ThemeProvider } from "@/components";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/context/auth";
import { getDictionary } from "../../../get-dictionary";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

const RootLayout = async ({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) => {
  const dictionary = await getDictionary(params.lang);
  return (
    <html lang={params.lang} suppressHydrationWarning>
      <body
        className={cn("bg-background font-sans antialiased", fontSans.variable)}
      >
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar dictionary={dictionary} lang={params.lang} />

            {children}
            <Toaster />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
