import type { Metadata } from "next";
import { Roboto_Serif as FontSans } from "next/font/google";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import { Locale } from "../../../i18n-config";
import { Navbar, ThemeProvider } from "@/components";
import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/context/auth";
import StoreProvider from "./StoreProvider";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  params: { lang: Locale };
}

const RootLayout: React.FC<Props> = async ({ params: { lang }, children }) => {
  return (
    <StoreProvider>
      <html lang={lang} suppressHydrationWarning>
        <body
          className={cn(
            "bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          <AuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Navbar lang={lang} />

              {children}
              <Toaster />
            </ThemeProvider>
          </AuthProvider>
        </body>
      </html>
    </StoreProvider>
  );
};

export default RootLayout;
